### ISSUE TITLE
Update the `ARTIFACT` of each microservice

### ISSUE THREAD

**Issue by asmijafar20** [moja-global/FLINT.Reporting#58]
**scripts update**
Each script contain the `ARTIFACT` variable. Update the `ARTIFACT` variable of each microservices with the microservices name. 
Currently we are fetching it by using the maven command (`mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout`).
. 

**To change the `ARTIFACT` variable in each microservices scripts**
1. Go to 'code/services'
2. Update the `install.sh` and `build.sh`.
3. Change the `ARTIFACT` variable with the name of the **Microservice** in place of maven command.

**Why we are doing this?**
We have removed the installation commands for `maven`, `java` and `jdk` in environment setup guide. So we need to update it in order to avoid conflicts during the environment setup of the Reporting tool.

**Comment by HarshCasper** [comment]
Fixed by #60
